micronaut:
  application:
    name: buttons
  server:
    port: 8082
datasources:
  default:
    url: jdbc:mysql://localhost:3306/buttoncnt
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    dialect: MYSQL
rabbitmq:
  uri: amqp://localhost:5672
  username: student
  password: student
